services:
    api-pharma:
        container_name: api-pharma
        build:
            context: ./api-pharma/vendor/laravel/sail/runtimes/8.1
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.1/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-81}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '/var/www/html'
        depends_on:
            - mongodb
        volumes:
            - './api-pharma:/var/www/html'
        networks:
            - sail
    vue-views:
        container_name: views-pharma
        build:
            context: ./ludys_views
            dockerfile: Dockerfile
        ports:
            - 8080:8080
        networks:
            - sail
    mongodb:
        container_name: pharma-mongo
        image: mongo
        ports:
            - 27017:27017
        volumes:
            - 'mongo-data:/data/db'
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    mongo-data:
        driver: local
